## Numpy array and basics
learn about numpy with chai aur code

In [4]:
import numpy as np

### creating array from list

In [6]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array: ", arr_2d)


1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


### List vs numpy array


In [8]:
py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)


np_array = np.array([1, 2, 3]) #element wise multiplication
print("Python array multiplication ", np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)



Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]

 List operation time:  0.16451764106750488

 Numpy operation time:  0.0030164718627929688


### creating array from scratch

In [10]:
zeros = np.zeros((3, 4))
print("zeros array: \n", zeros)

ones = np.ones((2, 3))
print("one array: \n", ones)

full = np.full((2, 2), 7)
print("full array: \n", full)

random = np.random.random((2, 3))
print("random array: \n", random)

sequence = np.arange(0, 11, 2)
print("sequnce array: \n", sequence)


zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.65275373 0.79758785 0.48735313]
 [0.95903278 0.44582806 0.18090603]]
sequnce array: 
 [ 0  2  4  6  8 10]


### Vector, Matrix and Tensor

In [12]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])
print("Matrix: ", matrix)

tensor = np.array([[[1, 2], [3, 4]], 
                   [[5, 6], [7, 8]]])
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [14]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
print("Shape ", arr.shape)
print("Dimension ", arr.ndim)
print("Size ", arr.size)
print("DType ", arr.dtype)

Shape  (2, 3)
Dimension  2
Size  6
DType  int32


### Array Reshaping

In [16]:
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3, 4))
print("\n Reshaped array ", reshaped)

flattened = reshaped.flatten()
print("\n Flattened array ", flattened)

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("\n raveled array ", raveled)

# Transpose
transpose = reshaped.T
print("\n Transposed array ", transpose)



Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


**INDEXING,SLICING**

In [18]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing", arr[2:7])
print("With Step", arr[1:8:2])
print("Negative indexing", arr[-3])

Basic Slicing [3 4 5 6 7]
With Step [2 4 6 8]
Negative indexing 8


In [32]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Specific element", arr_2d[1, 2])
print("Entire row: ", arr_2d[1])
print("Entire row: ", arr_2d[:, 1])

Specific element 6
Entire row:  [4 5 6]
Entire row:  [2 5 8]


**SORTING**

In [34]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted Array", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("Sorted 2D array by column", np.sort(arr_2d_unsorted, axis=0))

Sorted Array [1 1 2 3 4 5 6 9]
Sorted 2D array by column [[1 1]
 [2 2]
 [3 3]]


**BASIC MATHEMATICS OPERATIONS**

In [36]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [38]:
a + 2

array([3, 4, 5, 6])

In [40]:
a - 2

array([-1,  0,  1,  2])

In [42]:
a * 2

array([2, 4, 6, 8])

In [44]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [46]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [48]:
a ** 2

array([ 1,  4,  9, 16])

**STATISTICS OPERATIONS**

In [50]:
# Sample data
data = np.array([1, 2, 3, 4, 5])

In [52]:
# Mean (Average)
mean_value = np.mean(data)
print("Mean:", mean_value)

Mean: 3.0


In [54]:
# Median
median_value = np.median(data)
print("Median:", median_value)

Median: 3.0


In [56]:
# Standard Deviation
std_deviation = np.std(data)
print("Standard Deviation:", std_deviation)

Standard Deviation: 1.4142135623730951


In [58]:
# Minimum and Maximum
min_value = np.min(data)
max_value = np.max(data)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)

Minimum Value: 1
Maximum Value: 5


In [60]:
#Correlation Coefficient
# Example arrays
data1 = np.array([1, 2, 3, 4, 5])
data2 = np.array([5, 4, 3, 2, 1])

# Calculate the correlation coefficient
correlation = np.corrcoef(data1, data2)
print("Correlation Coefficient Matrix:\n", correlation)

Correlation Coefficient Matrix:
 [[ 1. -1.]
 [-1.  1.]]


**MATRIX OPERATIONS**

In [62]:
#Dot Product
# Define two 1D arrays (vectors)
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Calculate dot product
dot_product = np.dot(arr1, arr2)
print("Dot Product:", dot_product)

Dot Product: 32


In [66]:
# MATRIX MULTIPLICATION
# Define two 2D arrays (matrices)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
matrix_mult_np = np.matmul(arr1, arr2)
print("Matrix Multiplication using np.matmul:\n", matrix_mult_np)

Matrix Multiplication using np.matmul:
 [[19 22]
 [43 50]]


In [68]:
#Determinant
arr = np.array([[1, 2], [3, 4]])
determinant = np.linalg.det(arr)
print("Determinant:", determinant)

Determinant: -2.0000000000000004


In [70]:
#Inverse
arr = np.array([[1, 2], [3, 4]])

# Calculate inverse
inverse = np.linalg.inv(arr)
print("Inverse:\n", inverse)


Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [72]:
# Eigenvalues and Eigenvectors

arr = np.array([[1, 2], [3, 4]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(arr)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


**BROADCASTING**

In [74]:
# Define two arrays of different shapes
arr1 = np.array([[1, 2, 3], [4, 5, 6]])  # Shape: (2, 3)
arr2 = np.array([10, 20, 30])            # Shape: (3,)

# Add the two arrays using broadcasting
result = arr1 + arr2

print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("Result of Broadcasting Addition:\n", result)

Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [10 20 30]
Result of Broadcasting Addition:
 [[11 22 33]
 [14 25 36]]
